from time import sleep
import random
from espeak import espeak 
from gpiozero import Button
import subprocess

stories = ['King James Bible. In the beginning God created the heaven and the earth. And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters. And God said, Let there be light: and there was light.',
           'Philip Pullman, Northern Lights. Lyra and her daemon moved through the darkening Hall, taking care to keep to one side, out of sight of the kitchen. The three great tables that ran the length of the hall were laid already, the silver and the glass catching what little light there was, and the long benches were pulled out ready for the guests.',
           'Enid Blyton, The Magic Faraway Tree. There were once three children, called Jo,Bessie and Fanny. All their lives they had lived in a town, but now their farther had a job in the country so they all moved as soon as ever they could',
           'James Joyce, Ulysses. STATELY, PLUMP BUCK MULLIGAN CAME FROM THE STAIRHEAD, bearing a bowl of lather on which a mirror and a razor lay crossed. A yellow dressing gown, ungirdled, was sustained gently-behind him by the mild morning air. ',
            'Jane Austen, Pride and Prejudice. It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife. ',
           'Herman Melville, Moby Dick. Call me Ishmael. Some years ago - never mind how long precisely - having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world.',
            'J.K.Rowling, Harry Potter and the chamber of secrets. Not for the first time, an argument had broken out over breakfast at number four privet, privet drive. Mr Vernon Dursley had been woken in the early hours of the morning by a loud, hooting noise from his nephew Harrys room.',
            'J.R.R.Tolkein, The Hobbit. IN A HOLE in the ground there lived a hobbit. Not a nasty, dirty, wet hole, filled with the ends of worms and an oozy smell, nor yet a dry, bare, sandy hole with nothing in it to sit downon or to eat: it was a hobbit-hole, and that means comfort.',
           'Frances Hodgson Burnett, A Little Princess. Once on a dark winters day, When the yellow fog hung so thick and heavy in the streets of london that the lamps were lighted and the shop windows blazed with gas as they do at night, an odd looking little girl sat in a cab with her father, and was driven rather slowly through the big thoroughfares.',
            'Joan Aiken, Black Heart in Battersea. On a fine warm evening in late summer, over a hundred years ago, a boy might have been leading a donkey across Southwark Bridge in the City of London. The boy, who appeared to be about fifteen, was bright-eyed and black-haired, and looked as if he had spent most of his life out of doors;he carried a knapsack, and wore rough, warm garments of frieze. Both boy and donkey seemed a little bewildered by the crowds round about them; the streets were thronged with people strolling in the sunshine arter their days work.',
            'Joan Aiken, Night Birds on Nantucket. Late in the middle watch of a calm winters night, many years ago, a square-rigged, three-masted ship, the Sarah Cascket, was making her way slowly through northern seas, under a blaze of stars.',
            'E Nesbit, The Railway Children. They were not railway children to begin with. I dont suppose they had ever thought about railways except as a means of getting to Maskelyne and Cooks, the pantomime, Zoological Gardens and Mademe Tussauds. They were just ordinary suburban children, and they lived with their father and mother in an ordinary red-brick-fronted villa, with coloured glass in the front door, a tiled passage that was called a hall, a bathroom with hot and cold water, electric bells, French windows, and a good deal of white paint, and "every modern convenience", as the house-agents say.',
            'C.S.Lewis, The Lion the Witch and the Wardrobe. Once there were four children whose names were Peter, Susan, Edmund and Lucy. This story is about something that happened to them when they were sent away from London during the war because of the air-raids. they were sent to a house of an old professor who lived in the heart of the country ten miles from the nearest railway station and two miles to the nearest post office. he had no wife and he lived in a very lage house with a house keeper called Mrs Macready and three servants. (Their names were Ivy, Margaret and Betty, but they do not come into the story much. ) He himself was a very old man with shaggy white hair which grew over most of his face as well as on his head, and they liked him almost at once: but on the first evening when he came out to meet them at the front door he was so odd looking that Lucy ( who was the youngest) was a little afraid of him, and Edmund ( who was the next youngest) wanted to laugh and to keep on pretending that he was blowing his nose to hide it.',
            'Homer, The Odyssey. By now the other warriors, those that had escaped headlong ruin by sea or battle, were safely home. Only Odysseus tarried, shut up by Lady Calypso, a nymph and very Goddess, in her hewn-out caves.',
           'Dostoevsky, Crime and Punishment. Towards the end of a sultry afternoon early in July a young man came out of his little room in Stolyarny Lane and turned slowly and somewhat irresolutely in the direction of Kamenny Bridge.',
           'Franz Kafka, Metamorphoses. One morning, as Gregor Samsa was waking up from anxious dreams, he discovered that in bed he had been changed into a monstrous verminous bug. He lay on his armour-hard back and saw, as he lifted his head up a little, his brown, arched abdomen divided up into rigid bowlike sections. From this height the blanket, just about ready to slide off completely, could hardly stay in place. His numerous legs, pitifully thin in comparison to the rest of his circumference, flickered helplessly before his eyes.',
           'Charles Dickens, Great Expectations. My farthers family name being Pirrip, and my christian name Philip, my infant tongue could make of both names nothing longer or more explicit than Pip. So, i called myself Pip, and came to be called Pip.',
           'Francis Hodgson Burnett, The Secret Garden. When Mary Lenox was sent to Misselthwaite Manor to live with her uncle, everyone said she was the nost disagreaable-looking child ever seen. It was true, too. She had a little thin face and a little thin body, thin liight hair and a sour expression. Her hair was yellow and her face was yellow because she had been born in India and had always been ill in one way or another. Her father had help a position under the English Government and had always been busy and ill himself, and her mother had been a great beauty who cared only to go to partyies and amuse herself with gay people. She has not wanted a little girl at all, and when Mary was born she handed her over to the care of an Ayah, who was made to understand that if she wished to please the Memsahib she must keep the child out of sight as much as possible. So when she was a sickly, fretful, ugly little baby she was kept out of the way, and when she became a sickly, fretful toddling thing she was kept out of the way also. She never remembered seeing familiarly anything but the dark faces of her Ayah and the other native servants, and as they always obeyed her and gave her her own way in everything, because the Memsahib would be angry if she was disturbed by her crying, by the time she was six years old she was a tyrannical and selfish a little pig as ever lived. The young English governess who came to teach her to read and write disliked her so much that she gave up her place in three months, and when the other governesses came to try to fill it they always went away in a shorter time than the first one. So if Mary had not chosen really to want to know how to read books, she would never had learnt her letters at all.  ',
           'Charlotte Brontre, Shirley. Of the late years an abundant shower of curates has fallen upon the north of England: they lie very thick on the hills; every parish has one or more of them; they are young enough to be very active and ought to be doing a great deal of good. But not of late years are we about to speak. We are going back to the beginning of this century: late years - present years - are dusty, sunburnt, hot, arid. We will evade the noon - forget it in siesta, pass the mid day in slumber - and dream of dawn. ',
           'George Orwell, 1984. It was a bright cold day in April, and the clocks were striking thirteen. Winston Smith, his chin nuzzled into his breast in an effort to escape the vile wind, slipped quickly through the glass doors of Victory Mansions, though not quickly enough to prevent a swhirl of gritty dust entering along with him. ',
           'Daniel Defoe, Robinson Crusoe. I was born in the year sixteen thirty two, in the city of York, of a good family, tho not of that country, my father being a foreigner of Bremen, who settled first at Hull. He got a good estate by merchandise, and leaving off his trade lived afterward at York, from whence he had married my mother, whose relations were named Robinson, a very good family in that country, and from whom I was called Robinson Kreutznaer; but by the usual corruption of words in England, we are now called, nay, we call ourselves and write our name, Crusoe, and so my companions always called me. ',
           'Arthur Conan Doyle, Sherlock Holmes. To Sherlock Holmes she is always the woman. I have seldom hear him mention her under any other name. In his eyes she eclipses and predominates the whole of her sex. It was not that he felt any emotion akin to love for Irene Adler. All emotions, and that one particularly, were abhorent to his cold, precise, but admirabley balanced mind. He was, I take it, the most perfect reasoning and oserving machine that the world has seen: but, as a lover, he would have placed himself in a false position. He never spoke of the softer passions, save with a gibe and a sneer. They were admirable things for the observer - excellent for drawing the veil from mens motive and actions. But for the trained reasoner to admit such intrusions into his own delicate and finely adjusted temperament was to introduce a distracting factor which minght throw a doubt upon all his mental results. Grit in a sensitive instrument, or a crack in one of his high powered lenses, would not be more disturbing than a strong emotion in a nature such as his. And yet there was but one woman to him, and that woman was the late Irene Adler, of dubious and questionable memory. ',
           'H.P.Lovecraft, The Call of Cthulhu. The most merciful thing in the world, I think, is the inability of the human mind to correlate all its contence. We live on a placid island of ignorance in the midst of black seas of infinety, and it was not meant we should voyage far. the sciences, each straining in its own direction, have hitherto harmed as little; but some day the peicing together of dissociatded knoledge will open up such terrifying vistas of reality, and our frightful position therein, we shall either go mad from the revelation or flee from the deadly light into the peace and safety of a new dark age.',
            'F.Scott Fitzgerald, The Great Gatsby. In my younger and more vulnerable years my father gave me some advice that Ive been turning over in my mind ever since. "When ever you feel like criticizing anyone," he told me, "just remember that all the people in this world havent had the advantages that youve had."',
           'Joseph Heller, Catch 22. It was love at first sight. The first time Yossarian saw the chaplain he fell madly in love with him. Yossarian was in the hospital with a pain in his liver that fell just short of being jaundice. The doctors were puzzled by the fact that it wasnt quite jaundice. If it became jaundice they could treat it. If it didnt become jaundice and went away they could discharge him. But this just being short of jaundice all the time confused them.',
           'Laurence Stern, The Life and Opinions of Tristram Shandy, Gentleman. I wish that either my father or my mother, or indeed both of them, as they were in duty both equally bound to it, had minded what they were about when they begot me; had they duly considerd how much depended upon what they would then doing;- that not only the production of a rational Being was concernd in it, but that possibly the happy formation and temperature of his body, perhaps his genius and the very cast of his mind;- and, for aught they knew to the contrary, even the fortunes of his whole house might take their turn from the humours and dispositions which were then uppermost:- Had they duly weighed and considered all this, and proceeded acorrdingly,- I am varingly persuaded I should of made a quite a different ',
            'hello my name is mr googleypoo i am here to tell a story please press my nose again',
           ]
    
button = Button(17)

espeak.synth("Good morning! I am mr googleypoo and I am now alive")


while True:
    try:
        button.wait_for_press()
        espeak.synth("hello my name is mr googleypoo")
        sleep(2)
        subprocess.Popen(["espeak", "-p 8 -s 1 -k 20 -ven mb-en1", "-stdout | aplay",(random.choice(stories))])    
        sleep(20)

    except KeyboardInterrupt:
        break
